# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and publish

on:
  push:
    branches: [ "master" ]
    tags: ['v*']

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: build with go
      run: go build src/main.go

    - name: build dist
      run: bash build.sh biweekly-report-generator

    - name: version
      run: echo "::set-output name=version::$(date '+%Y.%j.%H.%M')"
      id: version

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload linux/amd64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/biweekly-report-generator-linux-amd64
        asset_name: biweekly-report-generator-linux-amd64
        asset_content_type: applicationapplication

    - name: upload windows/amd64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/biweekly-report-generator-windows-amd64.exe
        asset_name: biweekly-report-generator-windows-amd64.exe
        asset_content_type: applicationapplication

    - name: upload darwin/amd64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/biweekly-report-generator-darwin-amd64
        asset_name: biweekly-report-generator-darwin-amd64
        asset_content_type: applicationapplication

    - name: upload darwin/arm64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/biweekly-report-generator-darwin-arm64
        asset_name: biweekly-report-generator-darwin-arm64
        asset_content_type: applicationapplication